# Generated by Django 2.2.24 on 2026-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersso',
            name='id_persona',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
