# Generated by Django 2.2.24 on 2026-06-23 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eol_sso', '0002_auto_20260123_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIndivId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indiv_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
