# Generated by Django 2.2.24 on 2026-08-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eol_sso', '0003_userindivid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSso',
        ),
    ]
