name: Python application

on:
  push:
    branches:
      - 'eol-release/*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'eol-release/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test-eol
        run: |
          docker compose -f .github/docker-compose-koa.yml run --rm lms-eol /openedx/requirements/app/.github/test-eol.sh
      - name: test-open
        run: |
          docker compose -f .github/docker-compose-koa.yml run --rm lms-openuchile /openedx/requirements/app/.github/test-open.sh
